On 21 November 2024

idefix queries> ./benchmark.py --directory instance --engine MLocal --count --caching
Evaluating queries from instance, counted,
with caching allowed

# A set of instance queries, included because some are hard for Blazegraph.

QUERY: human-subclass All instances of human (Q5)
MLocal Elapsed= 7718ms Result=11463821

QUERY: human-subclass-labels All instances of human (Q5) with labels
MLocal Elapsed=246470ms Result=11463821

QUERY: human-subclass-labels All instances of human (Q5) with labels, label service for WDQS
MLocal Elapsed=30499ms Result=11463821

QUERY: protein-subclass All instances of protein (Q8054)
MLocal Elapsed=  619ms Result=1020817

QUERY: protein-subclass All instances of protein (Q8054), 2nd try
MLocal Elapsed=  545ms Result=1020817

QUERY: protein-subclass All instances of protein (Q8054), 3rd try
MLocal Elapsed=  559ms Result=1020817

QUERY: protein-subclass All instances of protein (Q8054), 4th try
MLocal Elapsed=  572ms Result=1020817

QUERY: protein-subclass-labels All instances of protein (Q8054) with labels
MLocal Elapsed=11185ms Result=1020817

QUERY: protein-subclass-labels All instances of protein (Q8054) with labels, label service for WDQS
MLocal Elapsed= 1716ms Result=1020817

QUERY: chemical-subclass All instances of chemical entity (Q43460564)
MLocal Elapsed= 1773ms Result=1164167

QUERY: concrete-subclass All instances of concrete object (Q4406616)
MLocal Elapsed=39000ms Result=32856470

QUERY: object-subclass All instances of object (Q488383)
MLocal Elapsed=159832ms Result=108140288

QUERY: entity-subclass All instances of entity (Q35120)
MLocal Elapsed=163596ms Result=110193552

QUERY: entity-subclass-labels All instances of entity (Q35120) with labels
MLocal Elapsed=531936ms EXCEPTION ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

QUERY: entity-subclass-labels All instances of entity (Q35120) with labels, label service for WDQS
MLocal Elapsed= 3117ms EXCEPTION HTTPConnectionPool(host='getafix', port=1234): Max retries exceeded with url: /sparql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3b8ac22120>: Failed to establish a new connection: [Errno 113] No route to host'))
